/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransitsRouteImport } from './routes/transits'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransitsSlugRouteImport } from './routes/transits.$slug'

const TransitsRoute = TransitsRouteImport.update({
  id: '/transits',
  path: '/transits',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitsSlugRoute = TransitsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TransitsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/transits': typeof TransitsRouteWithChildren
  '/transits/$slug': typeof TransitsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/transits': typeof TransitsRouteWithChildren
  '/transits/$slug': typeof TransitsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/transits': typeof TransitsRouteWithChildren
  '/transits/$slug': typeof TransitsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/library' | '/transits' | '/transits/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/library' | '/transits' | '/transits/$slug'
  id: '__root__' | '/' | '/about' | '/library' | '/transits' | '/transits/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LibraryRoute: typeof LibraryRoute
  TransitsRoute: typeof TransitsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transits': {
      id: '/transits'
      path: '/transits'
      fullPath: '/transits'
      preLoaderRoute: typeof TransitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transits/$slug': {
      id: '/transits/$slug'
      path: '/$slug'
      fullPath: '/transits/$slug'
      preLoaderRoute: typeof TransitsSlugRouteImport
      parentRoute: typeof TransitsRoute
    }
  }
}

interface TransitsRouteChildren {
  TransitsSlugRoute: typeof TransitsSlugRoute
}

const TransitsRouteChildren: TransitsRouteChildren = {
  TransitsSlugRoute: TransitsSlugRoute,
}

const TransitsRouteWithChildren = TransitsRoute._addFileChildren(
  TransitsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LibraryRoute: LibraryRoute,
  TransitsRoute: TransitsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
