/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignsRouteImport } from './routes/signs'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HousesRouteImport } from './routes/houses'
import { Route as CompatibilityRouteImport } from './routes/compatibility'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransitsIndexRouteImport } from './routes/transits.index'
import { Route as TransitsSlugRouteImport } from './routes/transits.$slug'
import { Route as LearnSiderealRouteImport } from './routes/learn.sidereal'
import { Route as CyclesSaturnTaurusRouteImport } from './routes/cycles.saturn-taurus'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignsRoute = SignsRouteImport.update({
  id: '/signs',
  path: '/signs',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesRoute = HousesRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => rootRouteImport,
} as any)
const CompatibilityRoute = CompatibilityRouteImport.update({
  id: '/compatibility',
  path: '/compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitsIndexRoute = TransitsIndexRouteImport.update({
  id: '/transits/',
  path: '/transits/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitsSlugRoute = TransitsSlugRouteImport.update({
  id: '/transits/$slug',
  path: '/transits/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSiderealRoute = LearnSiderealRouteImport.update({
  id: '/learn/sidereal',
  path: '/learn/sidereal',
  getParentRoute: () => rootRouteImport,
} as any)
const CyclesSaturnTaurusRoute = CyclesSaturnTaurusRouteImport.update({
  id: '/cycles/saturn-taurus',
  path: '/cycles/saturn-taurus',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/compatibility': typeof CompatibilityRoute
  '/houses': typeof HousesRoute
  '/library': typeof LibraryRoute
  '/signs': typeof SignsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cycles/saturn-taurus': typeof CyclesSaturnTaurusRoute
  '/learn/sidereal': typeof LearnSiderealRoute
  '/transits/$slug': typeof TransitsSlugRoute
  '/transits/': typeof TransitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/compatibility': typeof CompatibilityRoute
  '/houses': typeof HousesRoute
  '/library': typeof LibraryRoute
  '/signs': typeof SignsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cycles/saturn-taurus': typeof CyclesSaturnTaurusRoute
  '/learn/sidereal': typeof LearnSiderealRoute
  '/transits/$slug': typeof TransitsSlugRoute
  '/transits': typeof TransitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/compatibility': typeof CompatibilityRoute
  '/houses': typeof HousesRoute
  '/library': typeof LibraryRoute
  '/signs': typeof SignsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cycles/saturn-taurus': typeof CyclesSaturnTaurusRoute
  '/learn/sidereal': typeof LearnSiderealRoute
  '/transits/$slug': typeof TransitsSlugRoute
  '/transits/': typeof TransitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calculator'
    | '/compatibility'
    | '/houses'
    | '/library'
    | '/signs'
    | '/sitemap.xml'
    | '/cycles/saturn-taurus'
    | '/learn/sidereal'
    | '/transits/$slug'
    | '/transits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculator'
    | '/compatibility'
    | '/houses'
    | '/library'
    | '/signs'
    | '/sitemap.xml'
    | '/cycles/saturn-taurus'
    | '/learn/sidereal'
    | '/transits/$slug'
    | '/transits'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calculator'
    | '/compatibility'
    | '/houses'
    | '/library'
    | '/signs'
    | '/sitemap.xml'
    | '/cycles/saturn-taurus'
    | '/learn/sidereal'
    | '/transits/$slug'
    | '/transits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalculatorRoute: typeof CalculatorRoute
  CompatibilityRoute: typeof CompatibilityRoute
  HousesRoute: typeof HousesRoute
  LibraryRoute: typeof LibraryRoute
  SignsRoute: typeof SignsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CyclesSaturnTaurusRoute: typeof CyclesSaturnTaurusRoute
  LearnSiderealRoute: typeof LearnSiderealRoute
  TransitsSlugRoute: typeof TransitsSlugRoute
  TransitsIndexRoute: typeof TransitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signs': {
      id: '/signs'
      path: '/signs'
      fullPath: '/signs'
      preLoaderRoute: typeof SignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses': {
      id: '/houses'
      path: '/houses'
      fullPath: '/houses'
      preLoaderRoute: typeof HousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compatibility': {
      id: '/compatibility'
      path: '/compatibility'
      fullPath: '/compatibility'
      preLoaderRoute: typeof CompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transits/': {
      id: '/transits/'
      path: '/transits'
      fullPath: '/transits/'
      preLoaderRoute: typeof TransitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transits/$slug': {
      id: '/transits/$slug'
      path: '/transits/$slug'
      fullPath: '/transits/$slug'
      preLoaderRoute: typeof TransitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/sidereal': {
      id: '/learn/sidereal'
      path: '/learn/sidereal'
      fullPath: '/learn/sidereal'
      preLoaderRoute: typeof LearnSiderealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycles/saturn-taurus': {
      id: '/cycles/saturn-taurus'
      path: '/cycles/saturn-taurus'
      fullPath: '/cycles/saturn-taurus'
      preLoaderRoute: typeof CyclesSaturnTaurusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalculatorRoute: CalculatorRoute,
  CompatibilityRoute: CompatibilityRoute,
  HousesRoute: HousesRoute,
  LibraryRoute: LibraryRoute,
  SignsRoute: SignsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CyclesSaturnTaurusRoute: CyclesSaturnTaurusRoute,
  LearnSiderealRoute: LearnSiderealRoute,
  TransitsSlugRoute: TransitsSlugRoute,
  TransitsIndexRoute: TransitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
