/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignsRouteImport } from './routes/signs'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HousesRouteImport } from './routes/houses'
import { Route as ChartRouteImport } from './routes/chart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransitsIndexRouteImport } from './routes/transits.index'
import { Route as TransitsSlugRouteImport } from './routes/transits.$slug'
import { Route as LearnSiderealRouteImport } from './routes/learn.sidereal'
import { Route as LearnReadChartRouteImport } from './routes/learn.read-chart'
import { Route as CyclesSaturnTaurusRouteImport } from './routes/cycles.saturn-taurus'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignsRoute = SignsRouteImport.update({
  id: '/signs',
  path: '/signs',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesRoute = HousesRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartRoute = ChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitsIndexRoute = TransitsIndexRouteImport.update({
  id: '/transits/',
  path: '/transits/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitsSlugRoute = TransitsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TransitsRoute,
} as any)
const LearnSiderealRoute = LearnSiderealRouteImport.update({
  id: '/learn/sidereal',
  path: '/learn/sidereal',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnReadChartRoute = LearnReadChartRouteImport.update({
  id: '/learn/read-chart',
  path: '/learn/read-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const CyclesSaturnTaurusRoute = CyclesSaturnTaurusRouteImport.update({
  id: '/cycles/saturn-taurus',
  path: '/cycles/saturn-taurus',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chart': typeof ChartRoute
  '/houses': typeof HousesRoute
  '/library': typeof LibraryRoute
  '/signs': typeof SignsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cycles/saturn-taurus': typeof CyclesSaturnTaurusRoute
  '/learn/read-chart': typeof LearnReadChartRoute
  '/learn/sidereal': typeof LearnSiderealRoute
  '/transits/$slug': typeof TransitsSlugRoute
  '/transits/': typeof TransitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chart': typeof ChartRoute
  '/houses': typeof HousesRoute
  '/library': typeof LibraryRoute
  '/signs': typeof SignsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cycles/saturn-taurus': typeof CyclesSaturnTaurusRoute
  '/learn/read-chart': typeof LearnReadChartRoute
  '/learn/sidereal': typeof LearnSiderealRoute
  '/transits/$slug': typeof TransitsSlugRoute
  '/transits': typeof TransitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chart': typeof ChartRoute
  '/houses': typeof HousesRoute
  '/library': typeof LibraryRoute
  '/signs': typeof SignsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cycles/saturn-taurus': typeof CyclesSaturnTaurusRoute
  '/learn/read-chart': typeof LearnReadChartRoute
  '/learn/sidereal': typeof LearnSiderealRoute
  '/transits/$slug': typeof TransitsSlugRoute
  '/transits/': typeof TransitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chart'
    | '/houses'
    | '/library'
    | '/signs'
    | '/sitemap.xml'
    | '/cycles/saturn-taurus'
    | '/learn/read-chart'
    | '/learn/sidereal'
    | '/transits/$slug'
    | '/transits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chart'
    | '/houses'
    | '/library'
    | '/signs'
    | '/sitemap.xml'
    | '/cycles/saturn-taurus'
    | '/learn/read-chart'
    | '/learn/sidereal'
    | '/transits/$slug'
    | '/transits'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chart'
    | '/houses'
    | '/library'
    | '/signs'
    | '/sitemap.xml'
    | '/cycles/saturn-taurus'
    | '/learn/read-chart'
    | '/learn/sidereal'
    | '/transits/$slug'
    | '/transits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChartRoute: typeof ChartRoute
  HousesRoute: typeof HousesRoute
  LibraryRoute: typeof LibraryRoute
  SignsRoute: typeof SignsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CyclesSaturnTaurusRoute: typeof CyclesSaturnTaurusRoute
  LearnReadChartRoute: typeof LearnReadChartRoute
  LearnSiderealRoute: typeof LearnSiderealRoute
  TransitsIndexRoute: typeof TransitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signs': {
      id: '/signs'
      path: '/signs'
      fullPath: '/signs'
      preLoaderRoute: typeof SignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses': {
      id: '/houses'
      path: '/houses'
      fullPath: '/houses'
      preLoaderRoute: typeof HousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart': {
      id: '/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transits/': {
      id: '/transits/'
      path: '/transits'
      fullPath: '/transits/'
      preLoaderRoute: typeof TransitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transits/$slug': {
      id: '/transits/$slug'
      path: '/$slug'
      fullPath: '/transits/$slug'
      preLoaderRoute: typeof TransitsSlugRouteImport
      parentRoute: typeof TransitsRoute
    }
    '/learn/sidereal': {
      id: '/learn/sidereal'
      path: '/learn/sidereal'
      fullPath: '/learn/sidereal'
      preLoaderRoute: typeof LearnSiderealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/read-chart': {
      id: '/learn/read-chart'
      path: '/learn/read-chart'
      fullPath: '/learn/read-chart'
      preLoaderRoute: typeof LearnReadChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycles/saturn-taurus': {
      id: '/cycles/saturn-taurus'
      path: '/cycles/saturn-taurus'
      fullPath: '/cycles/saturn-taurus'
      preLoaderRoute: typeof CyclesSaturnTaurusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChartRoute: ChartRoute,
  HousesRoute: HousesRoute,
  LibraryRoute: LibraryRoute,
  SignsRoute: SignsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CyclesSaturnTaurusRoute: CyclesSaturnTaurusRoute,
  LearnReadChartRoute: LearnReadChartRoute,
  LearnSiderealRoute: LearnSiderealRoute,
  TransitsIndexRoute: TransitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
